# Generated by Django 4.2.8 on 2024-01-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_note_dream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='body',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
