# Generated by Django 4.2.8 on 2024-01-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dream_body_alter_dream_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='body',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
